sudo: required
language: php
php:
  - 7.0
services:
  - docker
os:
  - linux
before_script:
  - composer create-project --prefer-dist laravel/laravel html/lar
  - chmod -R 777 html/lar/public html/lar/storage html/lar/bootstrap/cache
  - docker --version
  - docker-compose --version
script:
  - docker-compose build
  - docker images
  - docker-compose up -d
  - sleep 20
  - docker ps
  - curl --retry 10 --retry-delay 5 -v http://localhost
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push vietdien2005/laravel_circleci
env:
  global:
  - secure: lSQzHAls4cguNc/B+epnSGLX8Sr6i5S/nKhIE4eDykJJYUj/YqyO4RrSHLt3T1hGcYcv/9VMwnJbLe+pYRfl6gob9qfSdHh5XZOyq3HlX0OklzUHTGzW4yaQ0ILBADquynGKiHEnpWTUGNtBMNeUXo1cvfqfTM2xEPK21azpsm+ClBiG4ip0Qa9CSI1Qg6twtApjWdkoVtgn6AIOr8qwpL6SZs5o5EBN8X8dXGCBKBbqsElkaUI+nwq0863rD1kjLXHu3S+c0m/G8vcD8clp41p6tKsTeEz64vxQ8dcvmzbhuPKkLv9AvHwfvallUVEal7Wbx03uZLTfnWeLRHCZpEhNE8ndfyxYLkSSod8dxnqwICdXy7MeHJxsw7GTUq5UT4OIe1gpqwdmJo+PMXXhVX4KRjZ1+Tt3fFK0edVwBe6ld7yEMhIx5CKPQ74FsXsoYcPCGTAXgftQeb4km1O3+kXNUQXrW5ra6DmgrUsgT8WVd+NeKVd2E/tQ1Wr2bnnnFK4+dfq1ZK05/e48GWRCkoPHQ6cA5uEbjv0e6anM9kGqAU9mWyRsNx8UTraqe8mVjwjDSe/41/Pp2navKAWkEpu2eadGXRCdLWspIsKwY/F2EkMCbeuEwFWZfuLVkwWzKtNW1Hin8CdHt+dVUFSfEEZSfwsBi+R6+Y2Wp/grK9g=
notifications:
  slack:
    rooms:
      secure: ScfpB3yV0y+HGpERfA3yO6GRJRVfgnwIjiDKpVU5ovcahK80l6oLGl06zSseLHlhxc/QAEKQbWg/76PzSdXT4D7IIcwgoEV4AtQpPj7QrWtI+95IhV7oIw9SYdbKCUK91vouL/qcjHNco55JaPOcRXPO+0o1bd17mSBuh971hA0nv2EeHkA6CP6hGU0cbG8a0OjSmsZ7e1I1mFfAunun19eMHH2MsskkYmxz2/ABU0QsZ3RWkonPl2uL+uCaTlF6Rual7TIE/zVBfkdj09OinVPZYZCOcuqAb7zveu/Ax3WrZb5ZMEP4R2pQpRS8Kbe6EDwHRSXwk6st6Y/8VMMF5MogYARujI6o2UKRdwkdjpiyj/QK4DedIzGedcPmrzO0vUuDTrt7LedmYOqC/BOc75LFPKNf5pgy5xueLx7OHX0hGuDZXXb68pixkQmf4V4VbCRbaRKSDdNVoSp0dPHnHfJP51jDRQ9HPSL2LgXDsap7nTnxXYu66Y/cWd0iflhE7J7redV37Bo/PyWxKgkSmzMQWCCnc/ueI0f+oD9i0F3HzFUrnkaJwqhZWInjhg+xhz26bf/4yWwT++a9iKBX8doP+SHjCVtKiD+fzElypCFtry9GgaqNvJ3SP05tPJtPAmEx+naBAND9bpRN4zs5MsVgSXg5w44k43H72yT0CLA=
